- name: demo on loops
  hosts: localhost
  vars:
   fruits:
     - apple
     - banana
     - orange
  tasks:
    - name: loop
      ansible.builtin.debug:
        msg: fruit - {{ item }}
      loop: " {{ fruits }}"  


      
